name: Deploy-doc-to-GitHub-Pages

on:
  push:
    branches:
      - main
permissions: 
  contents: write
jobs:
  docs_to_gh_pages:

    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Submodules
        run: |
          git submodule init
          git submodule update

      - name: Doxygen installation
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz

      - name: Doxygen generate documentation (csl::ag)
        run: |
          sudo mkdir -p docs/output/ag/
          sudo doxygen docs/details/ag.Doxyfile

      - name: Doxygen generate documentation (csl::wf)
        run: |
          sudo mkdir -p docs/output/wf/
          sudo doxygen docs/details/wf.Doxyfile

      - name: Generates host page (README)
        run: |
          cp README.md docs/
          cp docs/details/_config.yml docs/

      - name: Deploy 🚀 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
            branch: gh-pages
            folder: docs
