name: Deploy-doc-to-GitHub-Pages

on:
  push:
    branches:
      - main

jobs:
  docs_to_gh_pages:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
    - uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
          branch: main
          folder: docs
