name: Deploy-doc-to-GitHub-Pages

# on:
#   pull_request:
#     types:
#       - closed

# jobs:
#   if_merged:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#     - run: |
#         echo The PR was merged

on:
  push:
    branches:
      - main
permissions: 
  contents: write
jobs:
  docs_to_gh_pages:

    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04 # ubuntu-latest currently is ubuntu-20.04

    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Deploy ACE to docs/
        # replace symlink to awesome-code-element.js by the real file
        run: |
          rm docs/awesome-code-element.js
          cp awesome-code-element.js  docs/
          rm -rf docs/styles
          cp -a styles                docs/

      - name: Generates host page (README)
        run: |
          cp README.md                docs/

      - name: Showcase - plain doxygen
        run: |
          sudo doxygen docs/showcase/using_doxygen/demo.Doxyfile

      - name: Deploy 🚀 
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
            branch: gh-pages
            folder: docs
